# Generated by Django 2.2.3 on 2019-09-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oaxaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='points', verbose_name='Imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='points', verbose_name='Imagen 2 (opcional)')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='points', verbose_name='Imagen 2 (opcional)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Imágenes Pocitos',
            },
        ),
        migrations.CreateModel(
            name='Pocitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='points', verbose_name='Imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='points', verbose_name='Imagen 2 (opcional)')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='points', verbose_name='Imagen 2 (opcional)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Imágenes Pocitos',
            },
        ),
        migrations.CreateModel(
            name='SanRoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='points', verbose_name='Imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='points', verbose_name='Imagen 2 (opcional)')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='points', verbose_name='Imagen 2 (opcional)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Imágenes Pocitos',
            },
        ),
        migrations.CreateModel(
            name='Zacateros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='points', verbose_name='Imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='points', verbose_name='Imagen 2 (opcional)')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='points', verbose_name='Imagen 2 (opcional)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Imágenes Pocitos',
            },
        ),
    ]
