# Generated by Django 2.0.2 on 2019-05-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.CharField(max_length=100, null=True, verbose_name='Año'),
        ),
    ]
